/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.tables.CodeSystem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeSystemRecord extends UpdatableRecordImpl<CodeSystemRecord> implements Record5<Integer, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_system.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_system.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.code_system.version</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_system.version</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.code_system.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.code_system.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.code_system.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.code_system.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.code_system.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.code_system.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CodeSystem.CODE_SYSTEM.ID;
    }

    @Override
    public Field<String> field2() {
        return CodeSystem.CODE_SYSTEM.VERSION;
    }

    @Override
    public Field<Integer> field3() {
        return CodeSystem.CODE_SYSTEM.SOURCE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return CodeSystem.CODE_SYSTEM.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CodeSystem.CODE_SYSTEM.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public Integer component3() {
        return getSourceId();
    }

    @Override
    public Integer component4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public Integer value3() {
        return getSourceId();
    }

    @Override
    public Integer value4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public CodeSystemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CodeSystemRecord value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public CodeSystemRecord value3(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public CodeSystemRecord value4(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CodeSystemRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CodeSystemRecord values(Integer value1, String value2, Integer value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeSystemRecord
     */
    public CodeSystemRecord() {
        super(CodeSystem.CODE_SYSTEM);
    }

    /**
     * Create a detached, initialised CodeSystemRecord
     */
    public CodeSystemRecord(Integer id, String version, Integer sourceId, Integer createdBy, LocalDateTime createdAt) {
        super(CodeSystem.CODE_SYSTEM);

        setId(id);
        setVersion(version);
        setSourceId(sourceId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised CodeSystemRecord
     */
    public CodeSystemRecord(de.dataelementhub.dal.jooq.tables.pojos.CodeSystem value) {
        super(CodeSystem.CODE_SYSTEM);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setSourceId(value.getSourceId());
            setCreatedBy(value.getCreatedBy());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
