/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.tables.ValueDomainReference;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainReferenceRecord extends UpdatableRecordImpl<ValueDomainReferenceRecord> implements Record5<String, Integer, Integer, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.value_domain_reference.subset_uri</code>.
     */
    public void setSubsetUri(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.value_domain_reference.subset_uri</code>.
     */
    public String getSubsetUri() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.value_domain_reference.scopedidentifier_id</code>.
     */
    public void setScopedidentifierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.value_domain_reference.scopedidentifier_id</code>.
     */
    public Integer getScopedidentifierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.value_domain_reference.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.value_domain_reference.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.value_domain_reference.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.value_domain_reference.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.value_domain_reference.code_system_id</code>.
     */
    public void setCodeSystemId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.value_domain_reference.code_system_id</code>.
     */
    public Integer getCodeSystemId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, Integer, LocalDateTime, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Integer, Integer, LocalDateTime, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ValueDomainReference.VALUE_DOMAIN_REFERENCE.SUBSET_URI;
    }

    @Override
    public Field<Integer> field2() {
        return ValueDomainReference.VALUE_DOMAIN_REFERENCE.SCOPEDIDENTIFIER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_AT;
    }

    @Override
    public Field<Integer> field5() {
        return ValueDomainReference.VALUE_DOMAIN_REFERENCE.CODE_SYSTEM_ID;
    }

    @Override
    public String component1() {
        return getSubsetUri();
    }

    @Override
    public Integer component2() {
        return getScopedidentifierId();
    }

    @Override
    public Integer component3() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Integer component5() {
        return getCodeSystemId();
    }

    @Override
    public String value1() {
        return getSubsetUri();
    }

    @Override
    public Integer value2() {
        return getScopedidentifierId();
    }

    @Override
    public Integer value3() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public Integer value5() {
        return getCodeSystemId();
    }

    @Override
    public ValueDomainReferenceRecord value1(String value) {
        setSubsetUri(value);
        return this;
    }

    @Override
    public ValueDomainReferenceRecord value2(Integer value) {
        setScopedidentifierId(value);
        return this;
    }

    @Override
    public ValueDomainReferenceRecord value3(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ValueDomainReferenceRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ValueDomainReferenceRecord value5(Integer value) {
        setCodeSystemId(value);
        return this;
    }

    @Override
    public ValueDomainReferenceRecord values(String value1, Integer value2, Integer value3, LocalDateTime value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValueDomainReferenceRecord
     */
    public ValueDomainReferenceRecord() {
        super(ValueDomainReference.VALUE_DOMAIN_REFERENCE);
    }

    /**
     * Create a detached, initialised ValueDomainReferenceRecord
     */
    public ValueDomainReferenceRecord(String subsetUri, Integer scopedidentifierId, Integer createdBy, LocalDateTime createdAt, Integer codeSystemId) {
        super(ValueDomainReference.VALUE_DOMAIN_REFERENCE);

        setSubsetUri(subsetUri);
        setScopedidentifierId(scopedidentifierId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setCodeSystemId(codeSystemId);
    }

    /**
     * Create a detached, initialised ValueDomainReferenceRecord
     */
    public ValueDomainReferenceRecord(de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference value) {
        super(ValueDomainReference.VALUE_DOMAIN_REFERENCE);

        if (value != null) {
            setSubsetUri(value.getSubsetUri());
            setScopedidentifierId(value.getScopedidentifierId());
            setCreatedBy(value.getCreatedBy());
            setCreatedAt(value.getCreatedAt());
            setCodeSystemId(value.getCodeSystemId());
        }
    }
}
