/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.tables.ValueDomainDefinedPermissibleValue;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainDefinedPermissibleValueRecord extends TableRecordImpl<ValueDomainDefinedPermissibleValueRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.value_domain_defined_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public void setValueDomainScopedIdentifierId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.value_domain_defined_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public Integer getValueDomainScopedIdentifierId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.value_domain_defined_permissible_value.defined_permissible_value_scoped_identifier_id</code>.
     */
    public void setDefinedPermissibleValueScopedIdentifierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.value_domain_defined_permissible_value.defined_permissible_value_scoped_identifier_id</code>.
     */
    public Integer getDefinedPermissibleValueScopedIdentifierId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ValueDomainDefinedPermissibleValue.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE.VALUE_DOMAIN_SCOPED_IDENTIFIER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ValueDomainDefinedPermissibleValue.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE.DEFINED_PERMISSIBLE_VALUE_SCOPED_IDENTIFIER_ID;
    }

    @Override
    public Integer component1() {
        return getValueDomainScopedIdentifierId();
    }

    @Override
    public Integer component2() {
        return getDefinedPermissibleValueScopedIdentifierId();
    }

    @Override
    public Integer value1() {
        return getValueDomainScopedIdentifierId();
    }

    @Override
    public Integer value2() {
        return getDefinedPermissibleValueScopedIdentifierId();
    }

    @Override
    public ValueDomainDefinedPermissibleValueRecord value1(Integer value) {
        setValueDomainScopedIdentifierId(value);
        return this;
    }

    @Override
    public ValueDomainDefinedPermissibleValueRecord value2(Integer value) {
        setDefinedPermissibleValueScopedIdentifierId(value);
        return this;
    }

    @Override
    public ValueDomainDefinedPermissibleValueRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValueDomainDefinedPermissibleValueRecord
     */
    public ValueDomainDefinedPermissibleValueRecord() {
        super(ValueDomainDefinedPermissibleValue.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);
    }

    /**
     * Create a detached, initialised ValueDomainDefinedPermissibleValueRecord
     */
    public ValueDomainDefinedPermissibleValueRecord(Integer valueDomainScopedIdentifierId, Integer definedPermissibleValueScopedIdentifierId) {
        super(ValueDomainDefinedPermissibleValue.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);

        setValueDomainScopedIdentifierId(valueDomainScopedIdentifierId);
        setDefinedPermissibleValueScopedIdentifierId(definedPermissibleValueScopedIdentifierId);
    }

    /**
     * Create a detached, initialised ValueDomainDefinedPermissibleValueRecord
     */
    public ValueDomainDefinedPermissibleValueRecord(de.dataelementhub.dal.jooq.tables.pojos.ValueDomainDefinedPermissibleValue value) {
        super(ValueDomainDefinedPermissibleValue.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);

        if (value != null) {
            setValueDomainScopedIdentifierId(value.getValueDomainScopedIdentifierId());
            setDefinedPermissibleValueScopedIdentifierId(value.getDefinedPermissibleValueScopedIdentifierId());
        }
    }
}
