/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainDefinedPermissibleValue implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer valueDomainScopedIdentifierId;
    private Integer definedPermissibleValueScopedIdentifierId;

    public ValueDomainDefinedPermissibleValue() {}

    public ValueDomainDefinedPermissibleValue(ValueDomainDefinedPermissibleValue value) {
        this.valueDomainScopedIdentifierId = value.valueDomainScopedIdentifierId;
        this.definedPermissibleValueScopedIdentifierId = value.definedPermissibleValueScopedIdentifierId;
    }

    public ValueDomainDefinedPermissibleValue(
        Integer valueDomainScopedIdentifierId,
        Integer definedPermissibleValueScopedIdentifierId
    ) {
        this.valueDomainScopedIdentifierId = valueDomainScopedIdentifierId;
        this.definedPermissibleValueScopedIdentifierId = definedPermissibleValueScopedIdentifierId;
    }

    /**
     * Getter for
     * <code>public.value_domain_defined_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public Integer getValueDomainScopedIdentifierId() {
        return this.valueDomainScopedIdentifierId;
    }

    /**
     * Setter for
     * <code>public.value_domain_defined_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public void setValueDomainScopedIdentifierId(Integer valueDomainScopedIdentifierId) {
        this.valueDomainScopedIdentifierId = valueDomainScopedIdentifierId;
    }

    /**
     * Getter for
     * <code>public.value_domain_defined_permissible_value.defined_permissible_value_scoped_identifier_id</code>.
     */
    public Integer getDefinedPermissibleValueScopedIdentifierId() {
        return this.definedPermissibleValueScopedIdentifierId;
    }

    /**
     * Setter for
     * <code>public.value_domain_defined_permissible_value.defined_permissible_value_scoped_identifier_id</code>.
     */
    public void setDefinedPermissibleValueScopedIdentifierId(Integer definedPermissibleValueScopedIdentifierId) {
        this.definedPermissibleValueScopedIdentifierId = definedPermissibleValueScopedIdentifierId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ValueDomainDefinedPermissibleValue other = (ValueDomainDefinedPermissibleValue) obj;
        if (this.valueDomainScopedIdentifierId == null) {
            if (other.valueDomainScopedIdentifierId != null)
                return false;
        }
        else if (!this.valueDomainScopedIdentifierId.equals(other.valueDomainScopedIdentifierId))
            return false;
        if (this.definedPermissibleValueScopedIdentifierId == null) {
            if (other.definedPermissibleValueScopedIdentifierId != null)
                return false;
        }
        else if (!this.definedPermissibleValueScopedIdentifierId.equals(other.definedPermissibleValueScopedIdentifierId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.valueDomainScopedIdentifierId == null) ? 0 : this.valueDomainScopedIdentifierId.hashCode());
        result = prime * result + ((this.definedPermissibleValueScopedIdentifierId == null) ? 0 : this.definedPermissibleValueScopedIdentifierId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ValueDomainDefinedPermissibleValue (");

        sb.append(valueDomainScopedIdentifierId);
        sb.append(", ").append(definedPermissibleValueScopedIdentifierId);

        sb.append(")");
        return sb.toString();
    }
}
