/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainReference implements Serializable {

    private static final long serialVersionUID = 1L;

    private String subsetUri;
    private Integer scopedidentifierId;
    private Integer createdBy;
    private LocalDateTime createdAt;
    private Integer codeSystemId;

    public ValueDomainReference() {}

    public ValueDomainReference(ValueDomainReference value) {
        this.subsetUri = value.subsetUri;
        this.scopedidentifierId = value.scopedidentifierId;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.codeSystemId = value.codeSystemId;
    }

    public ValueDomainReference(
        String subsetUri,
        Integer scopedidentifierId,
        Integer createdBy,
        LocalDateTime createdAt,
        Integer codeSystemId
    ) {
        this.subsetUri = subsetUri;
        this.scopedidentifierId = scopedidentifierId;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.codeSystemId = codeSystemId;
    }

    /**
     * Getter for <code>public.value_domain_reference.subset_uri</code>.
     */
    public String getSubsetUri() {
        return this.subsetUri;
    }

    /**
     * Setter for <code>public.value_domain_reference.subset_uri</code>.
     */
    public void setSubsetUri(String subsetUri) {
        this.subsetUri = subsetUri;
    }

    /**
     * Getter for
     * <code>public.value_domain_reference.scopedidentifier_id</code>.
     */
    public Integer getScopedidentifierId() {
        return this.scopedidentifierId;
    }

    /**
     * Setter for
     * <code>public.value_domain_reference.scopedidentifier_id</code>.
     */
    public void setScopedidentifierId(Integer scopedidentifierId) {
        this.scopedidentifierId = scopedidentifierId;
    }

    /**
     * Getter for <code>public.value_domain_reference.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.value_domain_reference.created_by</code>.
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.value_domain_reference.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.value_domain_reference.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.value_domain_reference.code_system_id</code>.
     */
    public Integer getCodeSystemId() {
        return this.codeSystemId;
    }

    /**
     * Setter for <code>public.value_domain_reference.code_system_id</code>.
     */
    public void setCodeSystemId(Integer codeSystemId) {
        this.codeSystemId = codeSystemId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ValueDomainReference other = (ValueDomainReference) obj;
        if (this.subsetUri == null) {
            if (other.subsetUri != null)
                return false;
        }
        else if (!this.subsetUri.equals(other.subsetUri))
            return false;
        if (this.scopedidentifierId == null) {
            if (other.scopedidentifierId != null)
                return false;
        }
        else if (!this.scopedidentifierId.equals(other.scopedidentifierId))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.codeSystemId == null) {
            if (other.codeSystemId != null)
                return false;
        }
        else if (!this.codeSystemId.equals(other.codeSystemId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.subsetUri == null) ? 0 : this.subsetUri.hashCode());
        result = prime * result + ((this.scopedidentifierId == null) ? 0 : this.scopedidentifierId.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.codeSystemId == null) ? 0 : this.codeSystemId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ValueDomainReference (");

        sb.append(subsetUri);
        sb.append(", ").append(scopedidentifierId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(codeSystemId);

        sb.append(")");
        return sb.toString();
    }
}
