/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables;


import de.dataelementhub.dal.jooq.Keys;
import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.tables.records.CodeSystemRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeSystem extends TableImpl<CodeSystemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_system</code>
     */
    public static final CodeSystem CODE_SYSTEM = new CodeSystem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeSystemRecord> getRecordType() {
        return CodeSystemRecord.class;
    }

    /**
     * The column <code>public.code_system.id</code>.
     */
    public final TableField<CodeSystemRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.code_system.version</code>.
     */
    public final TableField<CodeSystemRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.code_system.source_id</code>.
     */
    public final TableField<CodeSystemRecord, Integer> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.code_system.created_by</code>.
     */
    public final TableField<CodeSystemRecord, Integer> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.code_system.created_at</code>.
     */
    public final TableField<CodeSystemRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private CodeSystem(Name alias, Table<CodeSystemRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodeSystem(Name alias, Table<CodeSystemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_system</code> table reference
     */
    public CodeSystem(String alias) {
        this(DSL.name(alias), CODE_SYSTEM);
    }

    /**
     * Create an aliased <code>public.code_system</code> table reference
     */
    public CodeSystem(Name alias) {
        this(alias, CODE_SYSTEM);
    }

    /**
     * Create a <code>public.code_system</code> table reference
     */
    public CodeSystem() {
        this(DSL.name("code_system"), null);
    }

    public <O extends Record> CodeSystem(Table<O> child, ForeignKey<O, CodeSystemRecord> key) {
        super(child, key, CODE_SYSTEM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CodeSystemRecord, Integer> getIdentity() {
        return (Identity<CodeSystemRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CodeSystemRecord> getPrimaryKey() {
        return Keys.CODE_SYSTEM_PKEY;
    }

    @Override
    public List<UniqueKey<CodeSystemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CODE_SYSTEM_SOURCE_ID_VERSION_KEY);
    }

    @Override
    public List<ForeignKey<CodeSystemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CODE_SYSTEM__SOURCE_ID_FKEY);
    }

    private transient Source _source;

    /**
     * Get the implicit join path to the <code>public.source</code> table.
     */
    public Source source() {
        if (_source == null)
            _source = new Source(this, Keys.CODE_SYSTEM__SOURCE_ID_FKEY);

        return _source;
    }

    @Override
    public CodeSystem as(String alias) {
        return new CodeSystem(DSL.name(alias), this);
    }

    @Override
    public CodeSystem as(Name alias) {
        return new CodeSystem(alias, this);
    }

    @Override
    public CodeSystem as(Table<?> alias) {
        return new CodeSystem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeSystem rename(String name) {
        return new CodeSystem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeSystem rename(Name name) {
        return new CodeSystem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeSystem rename(Table<?> name) {
        return new CodeSystem(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Class, Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
