/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables;


import de.dataelementhub.dal.jooq.Keys;
import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.tables.records.ValueDomainReferenceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainReference extends TableImpl<ValueDomainReferenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.value_domain_reference</code>
     */
    public static final ValueDomainReference VALUE_DOMAIN_REFERENCE = new ValueDomainReference();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ValueDomainReferenceRecord> getRecordType() {
        return ValueDomainReferenceRecord.class;
    }

    /**
     * The column <code>public.value_domain_reference.subset_uri</code>.
     */
    public final TableField<ValueDomainReferenceRecord, String> SUBSET_URI = createField(DSL.name("subset_uri"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.value_domain_reference.scopedidentifier_id</code>.
     */
    public final TableField<ValueDomainReferenceRecord, Integer> SCOPEDIDENTIFIER_ID = createField(DSL.name("scopedidentifier_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.value_domain_reference.created_by</code>.
     */
    public final TableField<ValueDomainReferenceRecord, Integer> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.value_domain_reference.created_at</code>.
     */
    public final TableField<ValueDomainReferenceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.value_domain_reference.code_system_id</code>.
     */
    public final TableField<ValueDomainReferenceRecord, Integer> CODE_SYSTEM_ID = createField(DSL.name("code_system_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ValueDomainReference(Name alias, Table<ValueDomainReferenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private ValueDomainReference(Name alias, Table<ValueDomainReferenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.value_domain_reference</code> table
     * reference
     */
    public ValueDomainReference(String alias) {
        this(DSL.name(alias), VALUE_DOMAIN_REFERENCE);
    }

    /**
     * Create an aliased <code>public.value_domain_reference</code> table
     * reference
     */
    public ValueDomainReference(Name alias) {
        this(alias, VALUE_DOMAIN_REFERENCE);
    }

    /**
     * Create a <code>public.value_domain_reference</code> table reference
     */
    public ValueDomainReference() {
        this(DSL.name("value_domain_reference"), null);
    }

    public <O extends Record> ValueDomainReference(Table<O> child, ForeignKey<O, ValueDomainReferenceRecord> key) {
        super(child, key, VALUE_DOMAIN_REFERENCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ValueDomainReferenceRecord> getPrimaryKey() {
        return Keys.VALUE_DOMAIN_REFERENCE_PKEY;
    }

    @Override
    public List<ForeignKey<ValueDomainReferenceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VALUE_DOMAIN_REFERENCE__CODE_SYSTEM_ID_FKEY);
    }

    private transient CodeSystem _codeSystem;

    /**
     * Get the implicit join path to the <code>public.code_system</code> table.
     */
    public CodeSystem codeSystem() {
        if (_codeSystem == null)
            _codeSystem = new CodeSystem(this, Keys.VALUE_DOMAIN_REFERENCE__CODE_SYSTEM_ID_FKEY);

        return _codeSystem;
    }

    @Override
    public ValueDomainReference as(String alias) {
        return new ValueDomainReference(DSL.name(alias), this);
    }

    @Override
    public ValueDomainReference as(Name alias) {
        return new ValueDomainReference(alias, this);
    }

    @Override
    public ValueDomainReference as(Table<?> alias) {
        return new ValueDomainReference(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainReference rename(String name) {
        return new ValueDomainReference(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainReference rename(Name name) {
        return new ValueDomainReference(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainReference rename(Table<?> name) {
        return new ValueDomainReference(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, Integer, LocalDateTime, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Class, Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
