/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables;


import de.dataelementhub.dal.jooq.Keys;
import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.tables.records.ValueDomainDefinedPermissibleValueRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainDefinedPermissibleValue extends TableImpl<ValueDomainDefinedPermissibleValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.value_domain_defined_permissible_value</code>
     */
    public static final ValueDomainDefinedPermissibleValue VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE = new ValueDomainDefinedPermissibleValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ValueDomainDefinedPermissibleValueRecord> getRecordType() {
        return ValueDomainDefinedPermissibleValueRecord.class;
    }

    /**
     * The column
     * <code>public.value_domain_defined_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public final TableField<ValueDomainDefinedPermissibleValueRecord, Integer> VALUE_DOMAIN_SCOPED_IDENTIFIER_ID = createField(DSL.name("value_domain_scoped_identifier_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.value_domain_defined_permissible_value.defined_permissible_value_scoped_identifier_id</code>.
     */
    public final TableField<ValueDomainDefinedPermissibleValueRecord, Integer> DEFINED_PERMISSIBLE_VALUE_SCOPED_IDENTIFIER_ID = createField(DSL.name("defined_permissible_value_scoped_identifier_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ValueDomainDefinedPermissibleValue(Name alias, Table<ValueDomainDefinedPermissibleValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private ValueDomainDefinedPermissibleValue(Name alias, Table<ValueDomainDefinedPermissibleValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.value_domain_defined_permissible_value</code> table
     * reference
     */
    public ValueDomainDefinedPermissibleValue(String alias) {
        this(DSL.name(alias), VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);
    }

    /**
     * Create an aliased
     * <code>public.value_domain_defined_permissible_value</code> table
     * reference
     */
    public ValueDomainDefinedPermissibleValue(Name alias) {
        this(alias, VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);
    }

    /**
     * Create a <code>public.value_domain_defined_permissible_value</code> table
     * reference
     */
    public ValueDomainDefinedPermissibleValue() {
        this(DSL.name("value_domain_defined_permissible_value"), null);
    }

    public <O extends Record> ValueDomainDefinedPermissibleValue(Table<O> child, ForeignKey<O, ValueDomainDefinedPermissibleValueRecord> key) {
        super(child, key, VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<ValueDomainDefinedPermissibleValueRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE__VALUE_DOMAIN_DEFINED_PERMISSI_VALUE_DOMAIN_SCOPED_IDENTIFI_FKEY, Keys.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE__VALUE_DOMAIN_DEFINED_PERMISSI_DEFINED_PERMISSIBLE_VALUE_SC_FKEY);
    }

    private transient ScopedIdentifier _valueDomainDefinedPermissiValueDomainScopedIdentifiFkey;
    private transient ScopedIdentifier _valueDomainDefinedPermissiDefinedPermissibleValueScFkey;

    /**
     * Get the implicit join path to the <code>public.scoped_identifier</code>
     * table, via the
     * <code>value_domain_defined_permissi_value_domain_scoped_identifi_fkey</code>
     * key.
     */
    public ScopedIdentifier valueDomainDefinedPermissiValueDomainScopedIdentifiFkey() {
        if (_valueDomainDefinedPermissiValueDomainScopedIdentifiFkey == null)
            _valueDomainDefinedPermissiValueDomainScopedIdentifiFkey = new ScopedIdentifier(this, Keys.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE__VALUE_DOMAIN_DEFINED_PERMISSI_VALUE_DOMAIN_SCOPED_IDENTIFI_FKEY);

        return _valueDomainDefinedPermissiValueDomainScopedIdentifiFkey;
    }

    /**
     * Get the implicit join path to the <code>public.scoped_identifier</code>
     * table, via the
     * <code>value_domain_defined_permissi_defined_permissible_value_sc_fkey</code>
     * key.
     */
    public ScopedIdentifier valueDomainDefinedPermissiDefinedPermissibleValueScFkey() {
        if (_valueDomainDefinedPermissiDefinedPermissibleValueScFkey == null)
            _valueDomainDefinedPermissiDefinedPermissibleValueScFkey = new ScopedIdentifier(this, Keys.VALUE_DOMAIN_DEFINED_PERMISSIBLE_VALUE__VALUE_DOMAIN_DEFINED_PERMISSI_DEFINED_PERMISSIBLE_VALUE_SC_FKEY);

        return _valueDomainDefinedPermissiDefinedPermissibleValueScFkey;
    }

    @Override
    public ValueDomainDefinedPermissibleValue as(String alias) {
        return new ValueDomainDefinedPermissibleValue(DSL.name(alias), this);
    }

    @Override
    public ValueDomainDefinedPermissibleValue as(Name alias) {
        return new ValueDomainDefinedPermissibleValue(alias, this);
    }

    @Override
    public ValueDomainDefinedPermissibleValue as(Table<?> alias) {
        return new ValueDomainDefinedPermissibleValue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainDefinedPermissibleValue rename(String name) {
        return new ValueDomainDefinedPermissibleValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainDefinedPermissibleValue rename(Name name) {
        return new ValueDomainDefinedPermissibleValue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValueDomainDefinedPermissibleValue rename(Table<?> name) {
        return new ValueDomainDefinedPermissibleValue(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link #convertFrom(Class, Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
