/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.daos;


import de.dataelementhub.dal.jooq.tables.CodeSystem;
import de.dataelementhub.dal.jooq.tables.records.CodeSystemRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeSystemDao extends DAOImpl<CodeSystemRecord, de.dataelementhub.dal.jooq.tables.pojos.CodeSystem, Integer> {

    /**
     * Create a new CodeSystemDao without any configuration
     */
    public CodeSystemDao() {
        super(CodeSystem.CODE_SYSTEM, de.dataelementhub.dal.jooq.tables.pojos.CodeSystem.class);
    }

    /**
     * Create a new CodeSystemDao with an attached configuration
     */
    public CodeSystemDao(Configuration configuration) {
        super(CodeSystem.CODE_SYSTEM, de.dataelementhub.dal.jooq.tables.pojos.CodeSystem.class, configuration);
    }

    @Override
    public Integer getId(de.dataelementhub.dal.jooq.tables.pojos.CodeSystem object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(CodeSystem.CODE_SYSTEM.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchById(Integer... values) {
        return fetch(CodeSystem.CODE_SYSTEM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.dataelementhub.dal.jooq.tables.pojos.CodeSystem fetchOneById(Integer value) {
        return fetchOne(CodeSystem.CODE_SYSTEM.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchOptionalById(Integer value) {
        return fetchOptional(CodeSystem.CODE_SYSTEM.ID, value);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchRangeOfVersion(String lowerInclusive, String upperInclusive) {
        return fetchRange(CodeSystem.CODE_SYSTEM.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchByVersion(String... values) {
        return fetch(CodeSystem.CODE_SYSTEM.VERSION, values);
    }

    /**
     * Fetch records that have <code>source_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchRangeOfSourceId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(CodeSystem.CODE_SYSTEM.SOURCE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source_id IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchBySourceId(Integer... values) {
        return fetch(CodeSystem.CODE_SYSTEM.SOURCE_ID, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchRangeOfCreatedBy(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(CodeSystem.CODE_SYSTEM.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchByCreatedBy(Integer... values) {
        return fetch(CodeSystem.CODE_SYSTEM.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(CodeSystem.CODE_SYSTEM.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.CodeSystem> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(CodeSystem.CODE_SYSTEM.CREATED_AT, values);
    }
}
