/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.daos;


import de.dataelementhub.dal.jooq.tables.ValueDomainReference;
import de.dataelementhub.dal.jooq.tables.records.ValueDomainReferenceRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainReferenceDao extends DAOImpl<ValueDomainReferenceRecord, de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference, Record2<Integer, Integer>> {

    /**
     * Create a new ValueDomainReferenceDao without any configuration
     */
    public ValueDomainReferenceDao() {
        super(ValueDomainReference.VALUE_DOMAIN_REFERENCE, de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference.class);
    }

    /**
     * Create a new ValueDomainReferenceDao with an attached configuration
     */
    public ValueDomainReferenceDao(Configuration configuration) {
        super(ValueDomainReference.VALUE_DOMAIN_REFERENCE, de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference object) {
        return compositeKeyRecord(object.getCodeSystemId(), object.getScopedidentifierId());
    }

    /**
     * Fetch records that have <code>subset_uri BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchRangeOfSubsetUri(String lowerInclusive, String upperInclusive) {
        return fetchRange(ValueDomainReference.VALUE_DOMAIN_REFERENCE.SUBSET_URI, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subset_uri IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchBySubsetUri(String... values) {
        return fetch(ValueDomainReference.VALUE_DOMAIN_REFERENCE.SUBSET_URI, values);
    }

    /**
     * Fetch records that have <code>scopedidentifier_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchRangeOfScopedidentifierId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ValueDomainReference.VALUE_DOMAIN_REFERENCE.SCOPEDIDENTIFIER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>scopedidentifier_id IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchByScopedidentifierId(Integer... values) {
        return fetch(ValueDomainReference.VALUE_DOMAIN_REFERENCE.SCOPEDIDENTIFIER_ID, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchRangeOfCreatedBy(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchByCreatedBy(Integer... values) {
        return fetch(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>code_system_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchRangeOfCodeSystemId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CODE_SYSTEM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code_system_id IN (values)</code>
     */
    public List<de.dataelementhub.dal.jooq.tables.pojos.ValueDomainReference> fetchByCodeSystemId(Integer... values) {
        return fetch(ValueDomainReference.VALUE_DOMAIN_REFERENCE.CODE_SYSTEM_ID, values);
    }
}
